"""fix profile g

Revision ID: 237c1d51b813
Revises: ec9c1e8ebce7
Create Date: 2026-04-21 20:29:48.228065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237c1d51b813'
down_revision: Union[str, Sequence[str], None] = 'ec9c1e8ebce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_table', 'target_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_table', 'target_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
