"""fix profile go go go

Revision ID: ec9c1e8ebce7
Revises: aa64c5405758
Create Date: 2026-04-21 19:57:48.068824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec9c1e8ebce7'
down_revision: Union[str, Sequence[str], None] = 'aa64c5405758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'description')
    # ### end Alembic commands ###
